name: Submit Ontology
description: Submit an ontology to the repository
title: "[Submission]: "
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting your ontology to the repository! Please fill out the following fields:
  - type: input
    id: ontology-name
    attributes:
      label: Ontology Name
      description: The name of your ontology
      placeholder: Comparative Constitutions Project Ontology
    validations:
      required: true
  - type: input
    id: ontology-label
    attributes:
      label: Ontology Label
      description: A short, all-caps label for your ontology (max. 8 characters)
      placeholder: CCP
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: Institution
      description: The parent institution for this ontology (if any)
      placeholder: Comparative Constitutions Project
    validations:
      required: false
  - type: textarea
    id: ontology-description
    attributes:
      label: Ontology Description
      description: A description of your ontology for public viewing. (Please don't upload any files here.)
    validations:
      required: true
  - type: input
    id: version-number
    attributes:
      label: Version number
      description: The version number. Must be sequential integers.
      placeholder: "1"
    validations:
      required: true
  - type: textarea
    id: version-notes
    attributes:
      label: Version notes
      description: What changes were made in this version? (Please don't upload any files here.)
      placeholder: Initial version
    validations:
      required: false
  - type: textarea
    id: citation
    attributes:
      label: Citation
      description: Citation for your ontology as BibTex entry. (Please don't upload any files here.)
    validations:
      required: false
  - type: textarea
    id: upload
    attributes:
      label: Ontology upload
      description: Please upload your .csv file here. See the required fields [here](https://github.com/conceptintegration/ontology-repo-test?tab=readme-ov-file#submit-your-own-ontology).
      placeholder: Initial version
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Your submission will be automatically processed by a bot and then it will be assigned to us for manual review. We'll be in touch. Thanks!
