name: Submit Ontology
description: Submit an ontology to the repository
title: "[Submission]: "
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting your ontology to the repository! Please fill out the following fields:
  - type: input
    id: ontology-name
    attributes:
      label: Ontology Name
      description: The name of your ontology
      placeholder: Comparative Constitutions Project Ontology
    validations:
      required: true
  - type: input
    id: ontology-label
    attributes:
      label: Ontology Label
      description: A short, all-caps label for your ontology (max. 8 characters)
      placeholder: CCP
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: Institution
      description: The parent institution for this ontology (if any)
      placeholder: Comparative Constitutions Project
    validations:
      required: false
  - type: textarea
    id: ontology-description
    attributes:
      label: Ontology Description
      description: A description of your ontology for public viewing
    validations:
      required: true
  - type: input
    id: version-number
    attributes:
      label: Version number
      description: The version number. Must be sequential integers.
      placeholder: 1
    validations:
      required: true
  - type: textarea
    id: version-notes
    attributes:
      label: Version notes
      description: What changes were made in this version?
      placeholder: Initital version
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Attached file
      description: Are you attaching an `ontology.csv` file with the [required fields](/)? To attach the file, simply drag-and-drop it to the form.
      options:
        - label: I am attaching the `ontology.csv` file.
          required: true
