name: Issue CSV Handler

on:
  issues:
    types: [opened]

jobs:
  process_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download issue attachments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          # (https://github.com/cli/cli/issues/9046#issuecomment-2381102664)
          # Fetch issue data
          echo "Fetching issue data..."
          ISSUE_DATA=$(gh issue view $ISSUE_NUMBER --json number,title,body,comments)
          echo "Issue data (BODY):"
          BODY=$("$ISSUE_DATA" | jq -r '.body')
          echo "$BODY"
          CSV_URLS=$(echo "$BODY" | grep -oP "https://github.com/user-attachments/files/.+/.+\.csv" | head -n 1)
          echo "URLS:"
          echo "$CSV_URL"
          if [[ -z "$CSV_URL" ]]; then
            echo "No CSV files found. Exiting."
            exit 0
          fi
          
          mkdir -p csv_files
          filename=$(basename "$CSV_URL")
          curl -H "Authorization: token $GITHUB_TOKEN" -L "$CSV_URL" -o "csv_files/$filename"
          done

      - name: Commit and push CSV files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add csv_files/*.csv
          git commit -m "Add CSV files from issue #${{ github.event.issue.number }}"
          git push
